{% set name = "dask-sql" %}
{% set version = "2024.1.0rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: 8a41362c469e95a0cfaeac93edc6ff4f68249b74c164398821b08a1688414b94

build:
  skip: true  # [py<39]
  entry_points:
    - dask-sql-server = dask_sql.server.app:main
    - dask-sql = dask_sql.cmd:main
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - pip
    - python
    - maturin
    - xz  # [linux64]
  run:
    - python
    - dask >=2022.3.0,<=2024.1.0
    - pandas >=1.4.0
    - fastapi >=0.92.0
    - httpx >=0.24.1
    - uvicorn >=0.13.4
    - tzlocal >=2.1
    - prompt-toolkit >=3.0.8
    - pygments >=2.7.1
    - tabulate

test:
  imports:
    - dask_sql
  commands:
    - pip check
    - dask-sql-server --help
    - dask-sql --help
  requires:
    - pip

about:
  home: https://github.com/dask-contrib/dask-sql/
  summary: SQL query layer for Dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ayushdg
    - quasiben
    - galipremsagar
    - charlesbluca
    - nils-braun
