{% set name = "dask-sql" %}
{% set version = "2021.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: 5d1d22225b9a21a44906110b74a702e66d8b30d2a4c6d4613848d2e79b22e333

build:
  number: 1
  skip: true   # [py2k]
  entry_points:
    - dask-sql-server = dask_sql.server.app:main
    - dask-sql = dask_sql.cmd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - maven >=3.6.0
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - python
    - dask >=2021.11.1,<=2021.11.2
    - pandas >=1.0.0
    - jpype1 >=1.0.2
    - openjdk >=8
    - fastapi >=0.61.1
    - uvicorn >=0.11.3
    - tzlocal >=2.1
    - prompt-toolkit
    - pygments
    - nest-asyncio
    - tabulate
    - importlib-metadata  # [py<38]

test:
  imports:
    - dask_sql
  commands:
    - pip check
    - dask-sql-server --help
    - dask-sql --help
  requires:
    - pip

about:
  home: http://github.com/dask-contrib/dask-sql/
  summary: SQL query layer for Dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - quasiben
    - galipremsagar
    - charlesbluca
    - nils-braun
