{% set name = "dask-sql" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: edb59cf82699f2fd260335641fd56b9b60932db39ee6a3cff3b0a720ca58578a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - maven >=3.6.0
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - python >=3.6
    - dask >=2.19.0,!=2021.3.0
    - pandas >=1.0.0
    - jpype1 >=1.0.2
    - openjdk >=8
    - fastapi >=0.61.1
    - uvicorn >=0.11.3
    - tzlocal >=2.1
    - prompt_toolkit >=3.0.8
    - pygments >=2.7.3
    - nest-asyncio >=1.0.0

test:
  imports:
    - dask_sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/nils-braun/dask-sql/
  summary: SQL Query Layer for dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - quasiben
    - galipremsagar
    - charlesbluca
    - nils-braun
