{% set name = "dask-sql" %}
{% set version = "2022.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dask-contrib/dask-sql/archive/{{ version }}.tar.gz
  sha256: 2841414cf628f8adb7517bde8c3033041bc943ae0612e9c627cdca97551d3c9d

build:
  skip: true  # [py<38 or arm64]
  entry_points:
    - dask-sql-server = dask_sql.server.app:main
    - dask-sql = dask_sql.cmd:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - setuptools-rust >=1.4.1
  host:
    - pip
    - python
    - setuptools-rust >=1.4.1
  run:
    - dask >=2022.3.0,<=2022.9.1
    - fastapi >=0.69.0
    - nest-asyncio
    - pandas >=1.4.0
    - prompt-toolkit
    - pygments
    - python
    - tabulate
    - tzlocal >=2.1
    - uvicorn >=0.11.3

test:
  imports:
    - dask_sql
  commands:
    - pip check
    - dask-sql-server --help
    - dask-sql --help
  requires:
    - pip

about:
  home: https://github.com/dask-contrib/dask-sql/
  summary: SQL query layer for Dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ayushdg
    - quasiben
    - galipremsagar
    - charlesbluca
    - nils-braun
