{% set name = "dask-sql" %}
{% set version = "2022.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: 460cf0c0cad6c7fcbac30341e8607ed6ae032d262b30fe7d686daede98737774

build:
  skip: true  # [py<38]
  entry_points:
    - dask-sql-server = dask_sql.server.app:main
    - dask-sql = dask_sql.cmd:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - setuptools-rust >=1.4.1
  host:
    - pip
    - python
    - setuptools-rust >=1.4.1
  run:
    - dask >=2022.3.0,<=2022.11.1
    - fastapi >=0.69.0
    - nest-asyncio
    - pandas >=1.4.0
    - prompt-toolkit >=3.0.8
    - pygments >=2.7.1
    - python
    - tabulate
    - tzlocal >=2.1
    - uvicorn >=0.13.4

test:
  imports:
    - dask_sql
  commands:
    - pip check
    - dask-sql-server --help
    - dask-sql --help
  requires:
    - pip

about:
  home: https://github.com/dask-contrib/dask-sql/
  summary: SQL query layer for Dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ayushdg
    - quasiben
    - galipremsagar
    - charlesbluca
    - nils-braun
